version: '3'
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    environment:
      - SA_PASSWORD=Msb123456
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
volumes:
  portainer_data: