spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=MSBBLOGDB
    username: SA
    password: Msb123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
